name: Integração Contínua (CI)

# Quando isso deve rodar?
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # O computador que o GitHub vai emprestar é um Linux

    steps:
    # 1. Baixar o seu código
    - name: Checkout do código
      uses: actions/checkout@v4

    # 2. Instalar o Python
    - name: Configurar Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # 3. Instalar as bibliotecas (Django, DRF, etc)
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Rodar os testes automatizados
    - name: Rodar Testes
      # Entramos na pasta store_api onde está o manage.py
      run: |
        cd store_api
        python manage.py test